boostcampwm-2021/web04-canyoufixme

- package.json
- packages/frontend/yarn.lock
- yarn.lock
> chore: CRA react 실행 안되는 이슈 해결(버전 이슈)

- .github/workflows/slack.yml
주요 브랜치를 제외한 브랜치를 push 이벤트로 부터 제거
> fix: 너무 빈번한 Slack 알림 감소

- .github/workflows/slack.yml
주요 브랜치를 제외한 브랜치를 push 이벤트로 부터 제거
> chore: 불필요한 슬랙 알림 감소

- .husky/prepare-commit-msg
- packages/backend/src/app.ts
- packages/frontend/package.json
- packages/frontend/src/components/NavLinkComponent.tsx
- packages/frontend/src/pages/DebugPage/debug.js
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/ListPage/index.tsx
- yarn.lock
- 문제 정보 비동기 로드 구현
- 문제 코드의 prettier 적용
- 특정 환경의 husky hook 미적용 버그 해결
> feat: 테스트 로직 구현 및 코드 에디터 prettier 적용

- packages/backend/src/app.ts
- packages/backend/src/controller/problemController.ts
- packages/backend/src/service/loginService.ts
- packages/backend/src/service/problemService.ts
- MongoDB에 문제에 대한 코드, 설명, 테스트 코드 저장
- Mysql에 문제에 대한 정보(제목, 언어, 출제자 etc.) 저장
Resolved #69
> feat: 문제 출제(등록) API 개발

- Dockerfile
- nginx.conf
- package.json
참고: https://docs.docker.com/engine/reference/builder/
> chore: Dockerfile multi-stage build로 변경

- .dockerignore
- Dockerfile
- 주요 환경변수가 이미지에 포함되지 않도록 보안조치
- 백엔드 기본포트 변경사항 적용
> chore: 백엔드 추가에 대응한 도커 이미지 빌드 옵션 개선

- .github/workflows/deploy.yml
> chore: 자동 배포 yml 파일 추가

- .github/workflows/deploy.yml
> fix: 자동 배포 yml 파일 root 경로 추가

- nginx.conf
참고: https://nginx.org/en/docs/http/ngx_http_core_module.html#try_files
Fixed #44
> chore: 새로고침 시의 nginx 라우팅 주소 404 오류 방지

- packages/backend/src/settings/ormConfig.ts
- `ormConfig.ts` 내의 `entities` 값을 객체 값으로 수정하였습니다.
> chore: ormconfig entities 배열 값을 import 객체 값으로 수정

- packages/debounce/examples/index.html
- packages/debounce/examples/index.js
- packages/debounce/index.d.ts
- packages/debounce/index.js
- packages/debounce/package.json
- 연속된 API 요청을 막기 위한 debounce 기능을 위한 `cyfm/debounce` 패키지 생성 및 기능 구현
> feat: debounce 패키지 추가

- packages/frontend/src/pages/DebugPage/index.tsx
> chore: 불필요한 쉼표 문자 제거

- packages/frontend/src/pages/DebugPage/debug.ts
- Backtick을 escape 처리
- iframe의 화면 노출 방지
> fix: Backtick 입력시 동작하지 않는 문제 수정 및 iframe 화면 노출 방지

- packages/backend/src/service/problemService.ts
- 무한 스크롤 기능을 적용하기 위해 문제 리스트를 불러오는 과정에서 query로 limit와 offset 쿼리를 적용할 수 있도록 변경
> feat: 문제 리스트 API에 offset과 limit 쿼리 적용

- packages/backend/src/model/User.ts
User 테이블과 JOIN시에 모든 컬럼이 기본으로 포함되는 문제를 수정
> fix: 불필요한 컬럼이 노출되지 않도록 조치

- packages/frontend/src/pages/ListPage/index.tsx
- packages/frontend/src/pages/ListPage/reducer.ts
> feat: 문제 리스트 페이지 무한 스크롤 기능 추가

- packages/backend/src/model/SubmitCode.ts
- packages/backend/src/model/SubmitLog.ts
submitCode에 testResult컬럼을 추가하였고,
submitLog에 OneToOne으로 잘못 설정된 관계를 ManyToOne으로 수정 및 codeId 컬럼을  추가했습니다.
> chore: submitCode, submitLog 모델 수정

- .gitignore
- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/components/Modal/ConfirmModal.tsx
- packages/frontend/src/components/Modal/LogoutModal.tsx
- packages/frontend/src/components/Modal/MessageModal.tsx
- packages/frontend/src/components/Modal/Modal.tsx
- packages/frontend/src/components/Modal/ModalButton.tsx
- yarn.lock
- `packages/frontend/src/components` 경로의 하위 폴더에 `Modal` 폴더를 생성
- 메세지 전달을 위한 Modal은 `MessageModal`을 사용
코드 리뷰 부탁드립니다.
> feat: Modal 레이아웃 생성 및 로그아웃 기능에 Modal 적용

- packages/backend/package.json
- packages/backend/src/app.ts
- packages/backend/src/controller/submitController.ts
- packages/backend/src/service/debugService.ts
- packages/backend/src/service/submitService.ts
- packages/backend/src/settings/socketConfig.ts
- packages/frontend/package.json
- packages/frontend/src/pages/DebugPage/index.tsx
- yarn.lock
- socket을 통한 코드 및 테스트 코드 전달 후 백엔드에서 채점
- 채점 결과를 socket을 통해 반환
- API 요청을 통해 채점 결과를 DB에 저장
- API 요청을 한번 더 한 이유 : socket으로 데이터를 전달할 때에 user 정보를 전달할 수 없기 때문이다.
- workerpool 안에서는 외부 모듈을 호출할 수 없으므로 chai를 사용하기 위해서는 빌드된 모듈 js를 파일 입력으로 읽어와서 사용해야 채점이 가능했다.
> feat: socket 연동 및 workerpool 적용(동시성 채점 구현)

- packages/backend/src/service/loginService.ts
- packages/backend/src/service/logoutService.ts
- login session에 대한 max-age의 싱크가 맞지 않는 이슈가 있어 max-age를 지정하여 싱크를 맞도록 수정했습니다.
- logout 시에 login session에 관련된 모든 쿠키를 제거하도록 수정했습니다.
> fix: login session 쿠키(isLogin)에 max-age 추가 및 logout 시 로직 일부 수정

- packages/backend/src/settings/socketConfig.ts
- yarn.lock
로컬과 도커 이미지 내 경로차이로 인해 실행이 불가한 문제 해결
참고: https://nodejs.org/api/modules.html#requireresolverequest-options
> fix: Docker 이미지 내에서의 경로 차이로 인한 실행 오류 수정

- packages/frontend/src/pages/WritePage/index.tsx
> fix: 출제 페이지에서 테스트 코드를 추가할 때 높이가 증가하는 현상 수정

- packages/backend/src/settings/socketConfig.ts
> fix: worker_thread 개수 5개로 설정

- README.md
- packages/styled/README.md
- CD GitHub Actions 상황 표시 배지 추가
- `@cyfm/styled` 패키지 README 추가
> docs: README 업데이트

- packages/frontend/craco.config.js
- packages/frontend/package.json
- packages/frontend/src/pages/DebugPage/sandbox.js
- yarn.lock
기본 CRA Webpack Terser 플러그인 설정으로 인해 매개변수가 minify 되어 오류가 발생하는 문제를
CRACO를 사용하여 덮어쓰기 하여 해결
참고: https://github.com/gsoft-inc/craco/tree/master/packages/craco#overridewebpackconfig
> fix: 샌드박스 매개변수가 minify 되어 오류가 발생하는 문제 수정

- packages/frontend/src/pages/DebugPage/index.tsx
- Socket 통신 과정에서 TimeoutError 발생 시 별도로 Modal 처리
> feat: Timeout 에러에 대한 Modal 처리

- packages/frontend/src/App.tsx
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- Message Modal 수정 과정에서 닫기 버튼이 사라진 현상 수정
> fix: Message Modal 닫기 버튼이 사라진 현상 수정

- README.md
> docs: readme 내용 수정

- packages/frontend/src/components/Modal/GuideModal.tsx
- packages/frontend/src/components/Modal/GuidelineCase.ts
- packages/frontend/src/pages/GuidePage/GuidelineCase.ts
- packages/frontend/src/pages/GuidePage/index.tsx
**작업 목록**
- 테스트케이스 가이드라인 `Modal` 생성
- 테스트케이스 가이드라인 페이지 생성
> feat: 테스트케이스 가이드라인 추가

- packages/frontend/src/App.tsx
- packages/frontend/src/contexts/SocketContext.ts
- packages/frontend/src/pages/DebugPage/index.tsx
**작업 목록**
- Context API를 사용하여 Socket을 전역 상태로 관리하도록 수정
- 문제 풀이 페이지 내에 있던 Socket 관련 코드를 삭제 (결과 페이지로 옮김)
> Refactor: Socket을 전역 상태로 관리하도록 수정

- packages/backend/src/service/debugService.ts
- packages/backend/src/settings/socketConfig.ts
- packages/frontend/src/App.tsx
- packages/frontend/src/components/ResultViewer.tsx
- packages/frontend/src/pages/ResultPage/enums.ts
- packages/frontend/src/pages/ResultPage/index.tsx
**작업 목록**
- 결과 페이지 및 `ResultViewer` 컴포넌트 생성
- 결과 처리를 테스트케이스마다 개별적으로 처리하도록 수정
> feat: 결과 페이지 생성

- packages/frontend/src/pages/DebugPage/index.tsx
- debug 페이지 history 중복 선언 제거 및 testCode 값 지정
> fix: debug 페이지 history 중복 선언 제거 및 testCode 값 지정

- packages/frontend/craco.config.js
- packages/frontend/package.json
- packages/frontend/src/pages/EditorPage/index.tsx
- packages/frontend/src/pages/EditorPage/module.d.ts
- packages/frontend/src/pages/EditorPage/sync.worker.js
- packages/frontend/tsconfig.json
- yarn.lock
https://user-images.githubusercontent.com/9497404/143024832-ec31cf66-35a5-471f-892a-edb5cba18c86.mov
SharedWorker를 사용하여 페이지 간 통신을 구현, 페이지 새로고침 없이 띄워놓은 모든 창을 동기화 가능하도록 기능 추가
참고:
- https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker
- https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope/connect_event
- https://www.npmjs.com/package/worker-plugin
> feat: 페이지 간 에디터 크기 동기화 기능 구현

- packages/backend/src/app.ts
- packages/backend/src/service/loginService.ts
- packages/backend/src/service/logoutService.ts
API 도메인이 변경되면서 발생한 세션 쿠키 교환문제를 해결
참고: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
> fix: API 도메인 변경에 따른 로그인 문제 해결

- .github/workflows/main-deploy.yml
- main branch에서 메인 서버로 배포 가능한 github action 작성 완료
- github action 동작 테스트 완료
- [링크](https://canyoufix.me)
> chore: main-branch github action 작성

- packages/frontend/src/App.tsx
- packages/frontend/src/components/FullWidthDiv/index.tsx
- packages/frontend/src/components/Modal/GuideModal.tsx
- packages/frontend/src/components/Modal/SelectModal.tsx
- packages/frontend/src/components/TestCodeEditor.tsx
- packages/frontend/src/components/TestCodeViewer.tsx
- packages/frontend/src/pages/WriteEditorPage/index.tsx
- packages/frontend/src/pages/WritePage/constant.ts
- packages/frontend/src/pages/WritePage/index.tsx
**작업 목록**
- 카테고리 및 레벨 선택을 위한 `SelectModal` 추가
- 문제 출제 페이지를 3등분하기 위해 `WriteEditorPage` 추가
- 테스트케이스 가이드 페이지 추가
- 문제 출제 시나리오 과정에서 필요한 메시지들을 `MessageModal`로 보이도록 적용
다음 주 리팩토링 시간에 `Modal` 작동에 관련된 상태들(`useState`)을 한 번에 관리할 수 있도록 `useReducer`로 리팩토링할 필요가 있음
> feat: 문제 출제 페이지 업데이트

- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/ResultPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
> chore: 터미널 및 devtool 콘솔의 표시 경고 제거

- packages/frontend/src/pages/DebugPage/debug.ts
- packages/frontend/src/pages/DebugPage/worker.js
오류로 인한 무한로딩 현상 수정
참고: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
> fix: Placeholder를 escape 처리 하도록 수정

- packages/backend/src/app.ts
- packages/backend/src/controller/statisticController.ts
- packages/backend/src/service/statisticService.ts
- 메인 페이지에서 사용할 데이터에 대한 api 개발
- 분리해서 개발 후 마지막 커밋에서 한번의 api 요청에서 데이터를 반환하도록 수정
> feat: 메인 페이지에서 사용할 데이터에 대한 api 개발

- packages/backend/src/service/statisticService.ts
- packages/frontend/src/pages/IntroPage/index.tsx
- statistic에 대한 데이터를 변환하는 로직을 프론트엔드에서 백엔드로 이동
> refactor: statistic에 대한 데이터를 변환하는 로직을 프론트엔드에서 백엔드로 이동

- packages/frontend/src/pages/DebugPage/index.tsx
- 문제 풀이 제출 시에 로그인 여부를 확인하고, 로그인이 안되어 있으면 모달 메세지를 띄움
> feat: 문제 풀이 제출 시 로그인 여부 확인

- .github/workflows/main-deploy.yml
- Dockerfile
- packages/backend/package.json
- 서버 실행 명령으로 `pm2-runtime`을 사용
- 모니터링을 위한 KEY 추가
> chore: PM2 설정 및 모니터링 KEY 추가

- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
**작업 목록**
- 문제 풀이 페이지 제출 버튼에 디바운스 적용
- 문제 출제 페이지 제출 버튼에 디바운스 적용
> feat: 문제 풀이 및 제출 페이지의 제출 버튼에 디바운스 적용

- packages/frontend/src/pages/EditorPage/index.tsx
아직 `SharedWorker`를 지원하는 브라우저가 많지 않은점을 고려
참고: https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker#browser_compatibility
> fix: SharedWorker 미지원 브라우저에 대한 예외처리 추가

- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- packages/throttle/examples/index.html
- packages/throttle/examples/index.js
- packages/throttle/index.d.ts
- packages/throttle/index.js
- packages/throttle/package.json
**작업 목록**
- debounce라 되어있는 부분을 전부 throttle로 변경했습니다.
P.S 용어를 제대로 알고 사용해야겠습니다...
> fix: debounce 패키지 명을 debounce에서 throttle로 변경

- packages/frontend/src/pages/ListPage/index.tsx
- packages/frontend/src/pages/ListPage/message.ts
- packages/frontend/src/pages/ListPage/reducer.ts
**작업 목록**
- 무한 로딩 시에 에러 메세지 Modal 추가
- 무한 스크롤 무한 로딩 및 정상 기능 안하던 오류 수정
> fix: 무한스크롤 무한 로딩 및 화면 크기에 따라 정상 기능 안하던 오류 수정

- packages/frontend/src/components/GitHubLoginButton/index.tsx
- packages/frontend/src/components/ResultViewer.tsx
- packages/frontend/src/pages/GuidePage/index.tsx
- packages/frontend/src/pages/NotFoundPage/index.tsx
`ReferenceError: React is not defined` 오류를 수정
> fix: 누락된 React import 추가

- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/DebugPage/reducer.ts
- packages/frontend/src/pages/IntroPage/index.tsx
- packages/frontend/src/pages/ListPage/index.tsx
**작업 목록**
- 문제 풀이 페이지 이동시 query로 카테고리를 넘겨주도록 구현
- debugReducer에 카테고리 추가
- 카테고리에 따라 코드 에디터 하이라이팅이 다르게 되도록 구현
> feat: 카테고리에 따라 코드 에디터 하이라이팅이 다르게 되도록 구현

- packages/backend/src/service/logoutService.ts
- packages/frontend/src/App.tsx
**작업 목록**
- 로그아웃 에러 발생 시 상태 코드(500)을 보내도록 변경
- 로그아웃 성공 여부를 메세지에서 상태 코드로 변경
> fix: 로그아웃이 안되는 문제를 수정

- packages/backend/src/setting/socketConfig.ts
- socketConfig 내 user없는 소켓 disconnect 부분을 submit 이벤트 안으로 이동
> fix: socketConfig 내 user없는 소켓 disconnect 부분을 submit 이벤트 안으로 이동

- packages/frontend/craco.config.js
- packages/frontend/package.json
- yarn.lock
↓
svgo 플러그인에서 `viewBox` 속성을 제거하여 발생하는 문제 해결
> chore: 로그인 버튼의 SVG 아이콘이 정상적으로 표시되지 않는 문제 수정

- packages/backend/src/setting/socketConfig.ts
- 부하 테스트 이후 `socketConfig.ts`에서 `socket.on('test')` 관련 이벤트 코드 제거
> refactor: 부하 테스트 이후 socketConfig에서 test 이벤트 관련 제거

- packages/frontend/src/pages/IntroPage/index.tsx
- packages/frontend/src/pages/IntroPage/message.ts
**작업 목록**
- 소개 페이지 빈 통계 데이터 처리
> feat: 소개 페이지 빈 통계 데이터 처리

- packages/backend/src/service/debugService.ts
- packages/types/src/entities.ts
**작업 목록**
- 테스트 타입 결과 확장하여 정의
- 누락된 `return`문 추가
> fix: 누락된 return문 추가

- packages/backend/src/service/debugService.ts
**작업 목록**
- 변수 result의 `const` 키워드 제거
> fix: result의 const 키워드 제거

- packages/backend/package.json
- packages/backend/src/service/debugService.ts
- packages/frontend/src/App.css
- packages/frontend/src/components/Console.tsx
- packages/frontend/src/hooks/useSandbox/debug.ts
- packages/frontend/src/hooks/useSandbox/index.ts
- packages/frontend/src/hooks/useSandbox/sandbox.js
- packages/frontend/src/hooks/useSandbox/worker.js
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- yarn.lock
https://user-images.githubusercontent.com/9497404/144268097-d6449aa1-4117-4506-a033-a032393197e6.mov
https://user-images.githubusercontent.com/9497404/144339803-40d523af-2124-43b3-9166-ee3ee56dee0e.mov
- https://sinonjs.org/releases/v12.0.1/fake-timers/
- https://sinonjs.org/releases/v12.0.1/sandbox/
> feat: 비동기 API 제공 및 콘솔 비동기 출력 지원

- packages/frontend/src/pages/WritePage/constant.ts
- packages/frontend/src/pages/WritePage/index.tsx
- packages/frontend/src/pages/WritePage/message.ts
- packages/frontend/src/pages/WritePage/reducer.ts
**작업 목록**
- 제출 전 코드 검증 과정 로직 추가
> feat: 문제 출제 전 코드 유효성 검증 로직 추가

- packages/frontend/src/pages/WritePage/index.tsx
> fix: 코드 검증 로직 순서 변경

- packages/frontend/src/pages/WritePage/message.ts
- 문제 리스트가 아닌 메인 페이지로 이동하므로 메세지 변ㄴ경
> fix: 출제 성공 메세지 변경
