boostcampwm-2021/web04-canyoufixme

- packages/frontend/package.json
- packages/frontend/src/App.css
- packages/frontend/src/App.tsx
- packages/frontend/src/components/Button.tsx
- packages/frontend/src/components/FullWidthViewer.tsx
- packages/frontend/src/components/TestCodeEditor.tsx
- packages/frontend/src/components/TestCodeViewer.tsx
- packages/frontend/src/hooks/useLogin.ts
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/EditorPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- packages/frontend/tsconfig.json
- packages/styled/index.js
- `Styled` 패키지에 `forwardRef`를 적용하여 하위 엘리먼트에 `Ref`를 적용 가능
- 문제 풀이 페이지와 문제 출제 페이지의 코드 에디터와 뷰어, 마크다운 에디터의 레이아웃 코드 분리
- 문제 출제 API POST 요청 기능 구현
> feat: 문제 출제 페이지

- Dockerfile
- Dockerfile 내의 다중 COPY 시 경로 설정 변경
- `.` => `./`
> fix: Dockerfile 내의 다중 COPY 시 경로 설정 변경

- Dockerfile
- packages/backend/package.json
- packages/backend/tsconfig.json
- `dist` 경로로 백엔드 JS 파일을 emit
- 캐시를 활용할 수 있도록 Dockerfile 명령 변경
- 배포환경 시작 스크립트 `start:prod` 명령 추가
> chore: 백엔드 배포환경 트랜스파일 빌드 적용

- packages/frontend/src/components/Modal/MessageModal.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- 제출 버튼 누른 뒤에 Confirm Modal이 보이지 않도록 제거
- 이동 Message Modal에서 닫기 버튼 제거
> fix: Modal 중복 제거 및 이동 시 닫기 버튼 제거

- .husky/commit-msg
- .husky/pre-commit
- 추가적인 [Conventional commits][1] 문법을 지원하도록 수정
- e.g. `fix!: `, `chore(docker): `
- 충돌 마커, 불필요한 공백이 커밋 대상 파일에 포함이 되어있는지에 대하여 검사하도록 수정
[1]: https://www.conventionalcommits.org/ko/v1.0.0-beta.4/
> chore: Husky 커밋 관련 훅 개선

- packages/backend/src/app.ts
- packages/backend/src/controller/submitController.ts
- packages/backend/src/service/submitService.ts
- packages/backend/src/service/userService.ts
- packages/backend/src/settings/socketConfig.ts
- packages/frontend/src/pages/DebugPage/index.tsx
- 채점 관련 http api 제거
- socket submit 이벤트 발생 시 채점을 진행하고 결과를 즉시 DB에 저장하도록 변경
(ps. 실시간으로 테스트 결과 하나하나 마다 따로 이벤트를 보내는 것은 회의 후 구현 예정)
> refactor: http api 방식에서 소켓 통신 방식으로 채점 결과를 저장하도록 방식 변경

- packages/backend/src/service/debugService.ts
- packages/backend/src/settings/socketConfig.ts
- 소켓 통신을 이용하여 실시간으로 테스트 결과값 전달
- 백엔드 로직 수정
- 에러 시 에러의 메시지를 전달하도록 수정
- 현재는 에러에 대한 문자열을 보내지만, 리팩토링 기간에 에러 코드를 전송하도록 수정할 예정
> refactor: 소켓 통신을 이용하여 실시간으로 테스트 결과값 전달

- packages/frontend/src/hooks/useBlockUnload.ts
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/DebugPage/reducer.ts
- packages/frontend/src/pages/WritePage/index.tsx
[history.block](https://v5.reactrouter.com/web/api/history) API도 존재하지만 적용시 popstate를 올바르게 처리하지 못하는 버그가 있어 직접 구현
- 페이지 이동 방지 custom hook 추가
- 문제 풀이 페이지 적용
- 문제 출제 페이지 적용
> feat: 에디터 수정시 페이지 이동 방지 기능 추가

- nginx.conf.template
- packages/backend/src/app.ts
- packages/backend/src/settings/socketConfig.ts
- packages/frontend/src/contexts/SocketContext.ts
백엔드 리버스 프록시 관련 GitHub OAuth 로그인, 소켓 세션 인증, `Set-Cookie` 세션 설정 헤더 등의 문제를 해결
- https://expressjs.com/ko/4x/api.html#app.set
- https://www.npmjs.com/package/express-session#user-content-cookiesecure
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
- https://socket.io/docs/v4/reverse-proxy/
- https://support.cloudflare.com/hc/ko/articles/200170786
> fix: 세션 관련 프록시 설정 추가

- nginx.conf.template
잘못된 upstream 블럭 위치로 인해 발생하는 오류를 수정
참고: https://nginx.org/en/docs/http/ngx_http_upstream_module.html
> fix: 잘못된 Nginx 설정 문법 수정

- packages/frontend/src/hooks/useBlockUnload.ts
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- 문제 풀이 및 출제 페이지에서 코드를 변경한 후, 제출 버튼을 눌러도 페이지 이동 `confirm` 창이 나오지 않도록 수정
> feat: 제출 버튼을 눌렀을때 이동 방지를 해제하도록 수정

- packages/frontend/src/pages/DebugPage/debug.ts
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/DebugPage/sandbox.js
- packages/frontend/src/pages/DebugPage/worker.js
BREAKING CHANGE:
- 백엔드로의 테스트 로직 이주의 후속으로 프론트엔드 테스트 로직 제거
- 컴포넌트의 `console.log` 렌더링 기능을 mocking으로 구현
> chore!: 프론트엔드 테스트로직 제거 및 콘솔 출력 구현

- packages/frontend/src/App.tsx
- packages/frontend/src/components/Modal/ConfirmModal.tsx
- packages/frontend/src/components/Modal/MessageModal.tsx
- packages/frontend/src/components/TestCodeEditor.tsx
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/DebugPage/message.ts
- packages/frontend/src/pages/WritePage/constant.ts
- packages/frontend/src/pages/WritePage/index.tsx
- packages/frontend/src/pages/WritePage/message.ts
**작업 목록**
- `message` props를 리스트에서 문자열로 변경
- 문제 풀이 페이지의 메세지를 별도의 파일로 분리
- 문제 출제 페이지의 상수와 메세지를 별도의 파일로 분리
> refactor: 상수 및 메세지를 페이지 파일로부터 분리

- packages/frontend/src/App.tsx
- packages/frontend/src/components/Modal/ConfirmModal.tsx
- packages/frontend/src/components/Modal/GuideModal.tsx
- packages/frontend/src/components/Modal/MessageModal.tsx
- packages/frontend/src/components/Modal/Modal.tsx
- packages/frontend/src/components/Modal/ModalType.ts
- packages/frontend/src/components/Modal/SelectModal.tsx
- packages/frontend/src/components/TestCodeEditor.tsx
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/DebugPage/message.ts
- packages/frontend/src/pages/DebugPage/reducer.ts
- packages/frontend/src/pages/WritePage/constant.ts
- packages/frontend/src/pages/WritePage/index.tsx
- packages/frontend/src/pages/WritePage/reducer.ts
**작업 목록**
- 케이스별로 생성되어있던 Message Modal을 통합
- Modal의 `setter`를 `React.dispatch`로 변경
- 각 페이지에서 Modal 상태 관리를 Reducer로 수정
> refactor: Modal 상태 관리를 Reducer로 수정

- .eslintrc.json
- Dockerfile
- packages/backend/package.json
- packages/backend/src/model/Problem.ts
- packages/backend/src/model/ProblemCode.ts
- packages/backend/src/model/SubmitCode.ts
- packages/backend/src/model/SubmitLog.ts
- packages/backend/src/model/User.ts
- packages/backend/src/service/statisticService.ts
- packages/backend/src/service/submitService.ts
- packages/frontend/package.json
- packages/frontend/src/components/Modal/GuideModal.tsx
- packages/frontend/src/components/Modal/GuidelineCase.ts
- packages/frontend/src/components/ResultViewer.tsx
- packages/frontend/src/pages/DebugPage/reducer.ts
- packages/frontend/src/pages/GuidePage/GuidelineCase.ts
- packages/frontend/src/pages/GuidePage/index.tsx
- packages/frontend/src/pages/IntroPage/index.tsx
- packages/frontend/src/pages/ListPage/index.tsx
- packages/frontend/src/pages/ListPage/reducer.ts
- packages/frontend/src/pages/ResultPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- packages/types/package.json
- packages/types/src/entities.ts
- packages/types/src/enums.ts
- packages/types/src/index.ts
- packages/types/tsconfig.json
- yarn.lock
- 백엔드와 프론트엔드, 양쪽에서 공통으로 사용되는 인터페이스를 추가
- 파일 내의 중복된 인터페이스, 타입을 패키지로 정리
- 명확하지 않은 이름을 변경
> refactor: 공통 타입 분리 및 인터페이스 추가

- .husky/prepare-commit-msg
> chore: 커밋 제목의 `%` 문자를 포맷문자로 인식하지 않도록 수정

- Dockerfile
- package.json
- packages/frontend/craco.config.js
- packages/frontend/package.json
- packages/frontend/src/components/Modal/GuideModal.tsx
- packages/frontend/src/components/Modal/ModalType.ts
- packages/frontend/src/pages/EditorPage/index.tsx
- packages/frontend/src/pages/IntroPage/index.tsx
- packages/frontend/src/pages/WriteEditorPage/index.tsx
- yarn.lock
`time docker build --no-cache` 결과
| 전 | 후 |
|---|---|
| ![image](https://user-images.githubusercontent.com/9497404/144058080-c2c72a8b-5c0b-4dfa-9fed-21ccdbea998d.png) | ![image](https://user-images.githubusercontent.com/9497404/144058119-02da18fc-d6e8-434c-9657-5542410c7dfc.png) |
- `@cyfm/types` 모듈이 빌드되지 않아 찾지 못하는 문제 수정 
- 프론트엔드 빌드에 esbuild 적용 (백엔드는 데코레이터 사용으로 인하여 적용 불가)
- https://esbuild.github.io/
- https://www.npmjs.com/package/craco-esbuild
- https://stackoverflow.com/q/52135815
> chore: 타입 빌드명령 추가 및 esbuild 적용을 통한 빌드 최적화

- packages/frontend/stressTest/loadTest.js
- 서버 채점까지 테스트한 경우 로그인 과정을 건너뛰고 테스트하였음(소켓에서 세션 넣어준 다음 실제처럼 실행되는 것은 실패)
- 소켓에 세션아이디 담아서 보내는 것이 안되었다.
> chore: 소켓 스트레스 테스트

- packages/frontend/src/hooks/useSandbox/debug.ts
- packages/frontend/src/hooks/useSandbox/index.ts
- `timeout` 이벤트 추가
- `error` 이벤트가 `dispatcher`를 통해 전달이 되지 않는 문제 수정
- `onError`, `onTimeout` 콜백 옵션 추가
> feat: 타임아웃 이벤트 추가 및 에러 이벤트 전달 문제 수정

- packages/frontend/src/pages/IntroPage/index.tsx
- packages/frontend/src/pages/ResultPage/index.tsx
- packages/frontend/src/pages/ResultPage/message.ts
- packages/frontend/src/pages/ResultPage/reducer.ts
**작업 목록**
- 결과 페이지에서 로그아웃 시 로그인 페이지로 리다이렉션
- 결과 페이지 에러 핸들링 추가
- 결과 페이지에서 문제 다시 풀기 및 문제 리스트로 가기 버튼 추가
- 소개 페이지에서 메세지 리스트에 누락된 `key` props 추가
> fix: 결과 페이지 로그아웃 시 데이터가 들어가는 버그 및 에러 핸들링

- packages/frontend/src/components/FullWidthViewer/styles.module.css
- packages/frontend/src/pages/DebugPage/index.tsx
- packages/frontend/src/pages/EditorPage/index.tsx
- packages/frontend/src/pages/WritePage/index.tsx
- 윈도우 환경에서 가로스크롤이 나타나는 현상 수정
- 콘텐츠 길이가 긴 경우, 마크다운 에디터의 배경색이 콘텐츠 높이에 맞게 적용되지 않는 현상 수정
> chore: 레이아웃 관련 문제 수정
